//MANAGER TYPES

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CANCEL_PROJECT = 'CANCEL_PROJECT';
export const OPEN_MEMBER_MODAL = 'OPEN_MEMBER_MODAL'
export const CLOSE_MEMBER_MODAL = 'CLOSE_MEMBER_MODAL'
export const OPEN_TASK_MODAL = 'OPEN_TASK_MODAL'
export const CLOSE_TASK_MODAL = 'CLOSE_TASK_MODAL' 
export const GET_ORGANIZATION_MEMBERS = 'GET_ORGANIZATION_MEMBERS'  //get software house members
export const SELECTED_MEMBERS = 'SELECTED_MEMBERS'
export const CLEAR_SELECTED_MEMBERS = 'CLEAR_SELECTED_MEMBERS'
export const SET_ASSIGNED_STATUS = 'SET_ASSIGNED_STATUS'

//ADMIN TYPES

// export const OPEN_FILTER_MODAL = 'OPEN_FILTER_MODAL'
// export const CLOSE_FILTER_MODAL = 'CLOSE_FILTER_MODAL'
export const OPEN_EDIT_MEMBER_MODAL = 'OPEN_EDIT_MEMBER_MODAL'
export const CLOSE_EDIT_MEMBER_MODAL = 'CLOSE_EDIT_MEMBER_MODAL'
export const OPEN_SOFTWARE_HOUSE_MODAL = 'OPEN_SOFTWARE_HOUSE_MODAL'
export const CLOSE_SOFTWARE_HOUSE_MODAL = 'CLOSE_SOFTWARE_HOUSE_MODAL'
export const GET_ORGANIZATION_DATA = 'GET_ORGANIZATION_DATA '
export const SET_CURRENT_ORGANIZATION = 'SET_CURRENT_ORGANIZATION'
export const GET_MEMBERS = 'GET_MEMBERS'
export const SET_CURRENT_MEMBER = 'SET_CURRENT_MEMBER'
export const FILTER_MEMBER = 'FILTER_MEMBER'
export const FILTER_ORGANIZATION = 'FILTER_ORGANIZATION'
export const CLEAR_FILTER = 'CLERA_FILTER'

//USERS

export const SET_USER_DATA = 'SET_USER_DATA'  //LogIn
export const USER_LOG_OUT = 'USER_LOG_OUT'
export const USER_SIGN_UP = 'USER_SIGN_UP'  //katana hai



